# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd95ffe9066463028cac53d88a9911a7a82c7ba36f98e4c744e694b46595f0a153d05f1c8879bcb05445ca81f5da343f671e8bed4d3b4de7dec6689016f46eeb

test:
  secret_key_base: 31bd2741a871c9cca8e10b46a80571b1c9c8c3d2eee78cf40083eec3953b8713a1a6849be6dcf5b5679fc513992d4174ea5ce2eb291fc141a22c63bb082ce1c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
